# Deployment file for clothing 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-clothing-dev
  labels:
    app: i27-clothing-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-clothing-dev
  template:
    metadata:
      labels:
        app: i27-clothing-dev
    spec:
      # imagePullSecrets:
      # - name: jfrog-registry
      containers:
      - name: i27-clothing-dev
        image: DIT # Image tag will be replaced by shared library
---
apiVersion: v1
kind: Service
metadata:
  name: i27-clothing-dev
  labels:
    app: i27-clothing-dev
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: i27-clothing-dev 